### ISSUE TITLE
Does not install on Windows 7-64 bit - Node 0.10.35

### ISSUE THREAD

**Issue by rcwwilliams** [stephenwvickers/node-raw-socket#10]
$ npm install net-ping
-
> raw-socket@1.4.0 install f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket
> node-gyp rebuild

f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket>node "e:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no
de-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  raw.cc
..\src\raw.cc(662): error C2039: 'Utf8String' : is not a member of 'v8::String' [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj
]
          C:\Users\Robin\.node-gyp\0.10.35\deps\v8\include\v8.h(1024) : see declaration of 'v8::String'
..\src\raw.cc(662): error C2065: 'Utf8String' : undeclared identifier [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(662): error C2146: syntax error : missing ';' before identifier 'address' [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw
.vcxproj]
..\src\raw.cc(662): error C2065: 'args' : undeclared identifier [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(662): error C3861: 'address': identifier not found [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(663): error C2065: 'address' : undeclared identifier [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(673): error C2039: 'Utf8String' : is not a member of 'v8::String' [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj
]
          C:\Users\Robin\.node-gyp\0.10.35\deps\v8\include\v8.h(1024) : see declaration of 'v8::String'
..\src\raw.cc(673): error C2065: 'Utf8String' : undeclared identifier [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(673): error C2146: syntax error : missing ';' before identifier 'address' [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw
.vcxproj]
..\src\raw.cc(673): error C3861: 'address': identifier not found [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
..\src\raw.cc(674): error C2065: 'address' : undeclared identifier [f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (e:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "e:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd f:\development\mean\SCR\server\node_modules\net-ping\node_modules\raw-socket
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.4.0 install script.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "e:\\Program Files\\nodejs\\node.exe" "e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "net-ping"
npm ERR! cwd f:\development\mean\SCR\server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by stephenwvickers** [comment]
Hi,

The most recent version of raw-socket has been tested only to work with Node.js 0.12.x and newer.

If you absolutely must support 0.10.x please let me know and I will see if I can get it working.

Thanks

Steve

**Comment by rcwwilliams** [comment]
Hi Steve

Thanks for getting back to me.

Thanks for your offer, but it's not a show stopper, so don't worry about it for now.

Kind regards

Robin

**Comment by stephenwvickers** [comment]
No worries, I'll close this ticket if you don't mind.  Just re-open if you want me to look further.

**Comment by erdmenchen** [comment]
I have the same output but for node v0.12.7. Have you tested it with this versions?
node v0.12.7
npm v2.11.3

Kind regards

**Comment by stephenwvickers** [comment]
Hi,

It has been tested with 0.12.x, I can't recall which version though.

Are you 100% sure it's the same issue?

I am more than happy to address any issues, but I need to know if it really is the same issue.

Do you have any output you can share?  An npm-debug.log?

Steve

**Comment by erdmenchen** [comment]
I am not that familiar with node and npm, so please excuse, if it is not the same issue.
But the errors are the same as rcwwilliams posted:

> 389 error Linux 2.6.32-573.3.1.el6.x86_64
390 error argv "/package/host/localhost/nodejs-0.12.7/bin/node" "/package/host/localhost/nodejs-0.12/bin/npm" "install"
391 error node v0.12.7
392 error npm  v2.11.3
393 error code ELIFECYCLE
394 error raw-socket@1.4.0 install: `node-gyp rebuild`
394 error Exit status 1
395 error Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
395 error This is most likely a problem with the raw-socket package,
395 error not with npm itself.
395 error Tell the author that this fails on your system:
395 error     node-gyp rebuild
395 error You can get their info via:
395 error     npm owner ls raw-socket
395 error There is likely additional logging output above.
396 verbose exit [ 1, true ]
397 verbose unbuild node_modules/net-ping/node_modules/raw-socket
398 info preuninstall raw-socket@1.4.0
399 info uninstall raw-socket@1.4.0
400 verbose unbuild rmStuff raw-socket@1.4.0 from /home/michal/NodeApps/uptime/node_modules
401 verbose unbuild rmStuff in /home/michal/NodeApps/uptime/node_modules/net-ping/node_modules
402 info postuninstall raw-socket@1.4.0
403 silly gentlyRm /home/michal/NodeApps/uptime/node_modules/net-ping/node_modules/raw-socket is being purged from base /home/michal/NodeApps/uptime
404 verbose gentlyRm don't care about contents; nuking /home/michal/NodeApps/uptime/node_modules/net-ping/node_modules/raw-socket
405 silly vacuum-fs purging /home/michal/NodeApps/uptime/node_modules/net-ping/node_modules/raw-socket
406 silly vacuum-fs removing /home/michal/NodeApps/uptime/node_modules/net-ping/node_modules
407 silly vacuum-fs quitting because other entries in /home/michal/NodeApps/uptime/node_modules/net-ping
408 verbose unbuild node_modules/net-ping
409 info preuninstall net-ping@1.1.12
410 info uninstall net-ping@1.1.12
411 verbose unbuild rmStuff net-ping@1.1.12 from /home/michal/NodeApps/uptime/node_modules
412 info postuninstall net-ping@1.1.12
413 silly gentlyRm /home/michal/NodeApps/uptime/node_modules/net-ping is being purged from base /home/michal/NodeApps/uptime
414 verbose gentlyRm don't care about contents; nuking /home/michal/NodeApps/uptime/node_modules/net-ping
415 silly vacuum-fs purging /home/michal/NodeApps/uptime/node_modules/net-ping
416 silly vacuum-fs quitting because other entries in /home/michal/NodeApps/uptime/node_modules

**Comment by stephenwvickers** [comment]
That doesn't look like the same issue, I don't see the same error messages.

I really need the npm-debug.log file, it should tell you the location in the output, which appears to have been cropped.

**Comment by erdmenchen** [comment]
So should I rather open a new ticket? Or just upload it right here?

Thank you for your support!

**Comment by erdmenchen** [comment]
Lets leave it for now, I wanted to check out a node.js app, that I just found out now, was discontinued last year.
So was for sure not an issue in raw-socket.

Thank you for your help anyway and keep the good work up!

**Comment by stephenwvickers** [comment]
No problem, if you want to continue troubleshooting let me know.
