### ISSUE TITLE
Enable all traffic 

### ISSUE THREAD

**Issue by ericsuarez** [stephenwvickers/node-raw-socket#32]
Hi, I am listening this [tutorial](http://www.binarytides.com/python-packet-sniffer-code-linux/) and I am asking if is posible to use the option socket.ntohs(0x0003) to capture all the traffic. Thanks

**Comment by ericsuarez** [comment]
My probem is:

When I analize the trafic. I saw that if a try to connect to a closed port in localhost. In the listen("message") I can see the flags syn and the response by the localhost of syn+rst

If a try to do the same with another machine in the same network, I only listen the syn of the other computer. The response of syn+rst is not visible. Can I solve this with the package?

**Comment by stephenwvickers** [comment]
Hi,

I am not familiar with the features that article describes, but it would seem like you need to create the socket with:

```
var socket = raw.createSocket ({protocol: 3})
```

However, what I would say is that I have seen where you have an application listening on say UDP port 53, opening a raw socket and attempting to capture this same data resulted in NOT receiving the packets because they were instead delivered to the application listening on UDP port 53.

You probably want to be using something like WinPCAP or libpcap.

Steve

**Comment by ericsuarez** [comment]
Thanks a lot Steve. :)
